main_benchmark:
  datasets:
    - clean
    - hard
    - high_res
  input_sizes:
    - 320
    - 640
    - 960

corruptions:
  types:
    - blur
    - noise
    - jpeg
  levels:
    - 1
    - 2
    - 3
  input_size: 640
